version: '3.7'

services:
  dnlp:
    restart: unless-stopped
    build: .
    ports:
      - "9090:80"
    expose:
      - 9090
    volumes:
      - fasttext:/fasttext
      - nltk_data:/root/nltk_data
    environment:
      LOG_LEVEL: "warning"
      ACCESS_LOG: ""

volumes:
    fasttext:
    nltk_data:
