from enum import Enum


# https://fasttext.cc/docs/en/language-identification.html
# Language Code =>
#   Language Family
#   ISO language name
#   Native name (endonym)
#   ISO 639-1
#   ISO 639-2/T
#   ISO 639-2/B
#   ISO 639-3
FASTTEXT_LANGUAGES = {
    'af': ('Indo-European', 'Afrikaans', 'Afrikaans', 'af', 'afr', 'afr', 'afr'),
    'sq': ('Indo-European', 'Albanian', 'Shqip', 'sq', 'sqi', 'alb', 'sqi'),
    'am': ('Afro-Asiatic', 'Amharic', 'አማርኛ', 'am', 'amh', 'amh', 'amh'),
    'ar': ('Afro-Asiatic', 'Arabic', 'العربية', 'ar', 'ara', 'ara', 'ara'),
    'an': ('Indo-European', 'Aragonese', 'aragonés', 'an', 'arg', 'arg', 'arg'),
    'hy': ('Indo-European', 'Armenian', 'Հայերեն', 'hy', 'hye', 'arm', 'hye'),
    'as': ('Indo-European', 'Assamese', 'অসমীয়া', 'as', 'asm', 'asm', 'asm'),
    'av': ('Northeast Caucasian', 'Avaric', 'авар мацӀ, магӀарул мацӀ', 'av', 'ava', 'ava', 'ava'),
    'az': ('Turkic', 'Azerbaijani', 'azərbaycan dili', 'az', 'aze', 'aze', 'aze'),
    'ba': ('Turkic', 'Bashkir', 'башҡорт теле', 'ba', 'bak', 'bak', 'bak'),
    'eu': ('Language isolate', 'Basque', 'euskara, euskera', 'eu', 'eus', 'baq', 'eus'),
    'be': ('Indo-European', 'Belarusian', 'беларуская мова', 'be', 'bel', 'bel', 'bel'),
    'bn': ('Indo-European', 'Bengali', 'বাংলা', 'bn', 'ben', 'ben', 'ben'),
    'bh': ('Indo-European', 'Bihari', 'भोजपुरी', 'bh', 'bih', 'bih', ''),
    'bs': ('Indo-European', 'Bosnian', 'bosanski jezik', 'bs', 'bos', 'bos', 'bos'),
    'br': ('Indo-European', 'Breton', 'brezhoneg', 'br', 'bre', 'bre', 'bre'),
    'bg': ('Indo-European', 'Bulgarian', 'български език', 'bg', 'bul', 'bul', 'bul'),
    'my': ('Sino-Tibetan', 'Burmese', 'ဗမာစာ', 'my', 'mya', 'bur', 'mya'),
    'ca': ('Indo-European', 'Catalan', 'català, valencià', 'ca', 'cat', 'cat', 'cat'),
    'ce': ('Northeast Caucasian', 'Chechen', 'нохчийн мотт', 'ce', 'che', 'che', 'che'),
    'zh': ('Sino-Tibetan', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'zh', 'zho', 'chi', 'zho'),
    'cv': ('Turkic', 'Chuvash', 'чӑваш чӗлхи', 'cv', 'chv', 'chv', 'chv'),
    'kw': ('Indo-European', 'Cornish', 'Kernewek', 'kw', 'cor', 'cor', 'cor'),
    'co': ('Indo-European', 'Corsican', 'corsu, lingua corsa', 'co', 'cos', 'cos', 'cos'),
    'hr': ('Indo-European', 'Croatian', 'hrvatski jezik', 'hr', 'hrv', 'hrv', 'hrv'),
    'cs': ('Indo-European', 'Czech', 'čeština, český jazyk', 'cs', 'ces', 'cze', 'ces'),
    'da': ('Indo-European', 'Danish', 'dansk', 'da', 'dan', 'dan', 'dan'),
    'dv': ('Indo-European', 'Divehi', 'ދިވެހި', 'dv', 'div', 'div', 'div'),
    'nl': ('Indo-European', 'Dutch', 'Nederlands, Vlaams', 'nl', 'nld', 'dut', 'nld'),
    'en': ('Indo-European', 'English', 'English', 'en', 'eng', 'eng', 'eng'),
    'eo': ('Constructed', 'Esperanto', 'Esperanto', 'eo', 'epo', 'epo', 'epo'),
    'et': ('Uralic', 'Estonian', 'eesti, eesti keel', 'et', 'est', 'est', 'est'),
    'fi': ('Uralic', 'Finnish', 'suomi, suomen kieli', 'fi', 'fin', 'fin', 'fin'),
    'fr': ('Indo-European', 'French', 'français, langue française', 'fr', 'fra', 'fre', 'fra'),
    'gl': ('Indo-European', 'Galician', 'Galego', 'gl', 'glg', 'glg', 'glg'),
    'ka': ('Kartvelian', 'Georgian', 'ქართული', 'ka', 'kat', 'geo', 'kat'),
    'de': ('Indo-European', 'German', 'Deutsch', 'de', 'deu', 'ger', 'deu'),
    'el': ('Indo-European', 'Greek', 'ελληνικά', 'el', 'ell', 'gre', 'ell'),
    'gn': ('Tupian', 'Guarani', 'Avañe\'ẽ', 'gn', 'grn', 'grn', 'grn'),
    'gu': ('Indo-European', 'Gujarati', 'ગુજરાતી', 'gu', 'guj', 'guj', 'guj'),
    'ht': ('Creole', 'Haitian', 'Kreyòl ayisyen', 'ht', 'hat', 'hat', 'hat'),
    'he': ('Afro-Asiatic', 'Hebrew', 'עברית', 'he', 'heb', 'heb', 'heb'),
    'hi': ('Indo-European', 'Hindi', 'हिन्दी, हिंदी', 'hi', 'hin', 'hin', 'hin'),
    'hu': ('Uralic', 'Hungarian', 'magyar', 'hu', 'hun', 'hun', 'hun'),
    'ia': ('Constructed', 'Interlingua', 'Interlingua', 'ia', 'ina', 'ina', 'ina'),
    'id': ('Austronesian', 'Indonesian', 'Bahasa Indonesia', 'id', 'ind', 'ind', 'ind'),
    'ie': ('Constructed', 'Interlingue', 'Interlingue', 'ie', 'ile', 'ile', 'ile'),
    'ga': ('Indo-European', 'Irish', 'Gaeilge', 'ga', 'gle', 'gle', 'gle'),
    'io': ('Constructed', 'Ido', 'Ido', 'io', 'ido', 'ido', 'ido'),
    'is': ('Indo-European', 'Icelandic', 'Íslenska', 'is', 'isl', 'ice', 'isl'),
    'it': ('Indo-European', 'Italian', 'Italiano', 'it', 'ita', 'ita', 'ita'),
    'ja': ('Japonic', 'Japanese', '日本語 (にほんご)', 'ja', 'jpn', 'jpn', 'jpn'),
    'jv': ('Austronesian', 'Javanese', 'ꦧꦱꦗꦮ, Basa Jawa', 'jv', 'jav', 'jav', 'jav'),
    'kn': ('Dravidian', 'Kannada', 'ಕನ್ನಡ', 'kn', 'kan', 'kan', 'kan'),
    'kk': ('Turkic', 'Kazakh', 'қазақ тілі', 'kk', 'kaz', 'kaz', 'kaz'),
    'km': ('Austroasiatic', 'Central Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'km', 'khm', 'khm', 'khm'),
    'ky': ('Turkic', 'Kirghiz', 'Кыргызча, Кыргыз тили', 'ky', 'kir', 'kir', 'kir'),
    'kv': ('Uralic', 'Komi', 'коми кыв', 'kv', 'kom', 'kom', 'kom'),
    'ko': ('Koreanic', 'Korean', '한국어', 'ko', 'kor', 'kor', 'kor'),
    'ku': ('Indo-European', 'Kurdish (Kurmanji)', 'Kurdî, کوردی‎', 'ku', 'kur', 'kur', 'kur'),
    'la': ('Indo-European', 'Latin', 'latine, lingua latina', 'la', 'lat', 'lat', 'lat'),
    'lb': ('Indo-European', 'Luxembourgish', 'Lëtzebuergesch', 'lb', 'ltz', 'ltz', 'ltz'),
    'li': ('Indo-European', 'Limburgish', 'Limburgs', 'li', 'lim', 'lim', 'lim'),
    'lo': ('Tai–Kadai', 'Lao', 'ພາສາລາວ', 'lo', 'lao', 'lao', 'lao'),
    'lt': ('Indo-European', 'Lithuanian', 'lietuvių kalba', 'lt', 'lit', 'lit', 'lit'),
    'lv': ('Indo-European', 'Latvian', 'latviešu valoda', 'lv', 'lav', 'lav', 'lav'),
    'gv': ('Indo-European', 'Manx', 'Gaelg, Gailck', 'gv', 'glv', 'glv', 'glv'),
    'mk': ('Indo-European', 'Macedonian', 'македонски јазик', 'mk', 'mkd', 'mac', 'mkd'),
    'mg': ('Austronesian', 'Malagasy', 'fiteny malagasy', 'mg', 'mlg', 'mlg', 'mlg'),
    'ms': ('Austronesian', 'Malay', 'Bahasa Melayu, بهاس ملايو‎', 'ms', 'msa', 'may', 'msa'),
    'ml': ('Dravidian', 'Malayalam', 'മലയാളം', 'ml', 'mal', 'mal', 'mal'),
    'mt': ('Afro-Asiatic', 'Maltese', 'Malti', 'mt', 'mlt', 'mlt', 'mlt'),
    'mr': ('Indo-European', 'Marathi', 'मराठी', 'mr', 'mar', 'mar', 'mar'),
    'mn': ('Mongolic', 'Mongolian', 'Монгол хэл', 'mn', 'mon', 'mon', 'mon'),
    'ne': ('Indo-European', 'Nepali', 'नेपाली', 'ne', 'nep', 'nep', 'nep'),
    'nn': ('Indo-European', 'Norwegian (Nynorsk)', 'Norsk Nynorsk', 'nn', 'nno', 'nno', 'nno'),
    'no': ('Indo-European', 'Norwegian (Bokmål)', 'Norsk', 'no', 'nor', 'nor', 'nor'),
    'oc': ('Indo-European', 'Occitan', 'occitan, lenga d\'òc', 'oc', 'oci', 'oci', 'oci'),
    'or': ('Indo-European', 'Oriya', 'ଓଡ଼ିଆ', 'or', 'ori', 'ori', 'ori'),
    'os': ('Indo-European', 'Ossetian', 'ирон æвзаг', 'os', 'oss', 'oss', 'oss'),
    'pa': ('Indo-European', 'Eastern Punjabi', 'ਪੰਜਾਬੀ', 'pa', 'pan', 'pan', 'pan'),
    'fa': ('Indo-European', 'Persian', 'فارسی', 'fa', 'fas', 'per', 'fas'),
    'pl': ('Indo-European', 'Polish', 'język polski, polszczyzna', 'pl', 'pol', 'pol', 'pol'),
    'ps': ('Indo-European', 'Pashto', 'پښتو', 'ps', 'pus', 'pus', 'pus'),
    'pt': ('Indo-European', 'Portuguese', 'Português', 'pt', 'por', 'por', 'por'),
    'qu': ('Quechuan', 'Quechua', 'Runa Simi, Kichwa', 'qu', 'que', 'que', 'que'),
    'rm': ('Indo-European', 'Romansh', 'Rumantsch Grischun', 'rm', 'roh', 'roh', 'roh'),
    'ro': ('Indo-European', 'Romanian', 'Română', 'ro', 'ron', 'rum', 'ron'),
    'ru': ('Indo-European', 'Russian', 'русский', 'ru', 'rus', 'rus', 'rus'),
    'sa': ('Indo-European', 'Sanskrit', 'संस्कृतम्', 'sa', 'san', 'san', 'san'),
    'sc': ('Indo-European', 'Sardinian', 'sardu', 'sc', 'srd', 'srd', 'srd'),
    'sd': ('Indo-European', 'Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'sd', 'snd', 'snd', 'snd'),
    'sr': ('Indo-European', 'Serbian', 'српски језик', 'sr', 'srp', 'srp', 'srp'),
    'gd': ('Indo-European', 'Scottish Gaelic', 'Gàidhlig', 'gd', 'gla', 'gla', 'gla'),
    'si': ('Indo-European', 'Sinhalese', 'සිංහල', 'si', 'sin', 'sin', 'sin'),
    'sk': ('Indo-European', 'Slovak', 'Slovenčina, Slovenský Jazyk', 'sk', 'slk', 'slo', 'slk'),
    'sl': ('Indo-European', 'Slovenian', 'Slovenski Jezik, Slovenščina', 'sl', 'slv', 'slv', 'slv'),
    'so': ('Afro-Asiatic', 'Somali', 'Soomaaliga, af Soomaali', 'so', 'som', 'som', 'som'),
    'es': ('Indo-European', 'Spanish', 'Español', 'es', 'spa', 'spa', 'spa'),
    'su': ('Austronesian', 'Sundanese', 'Basa Sunda', 'su', 'sun', 'sun', 'sun'),
    'sw': ('Niger–Congo', 'Swahili', 'Kiswahili', 'sw', 'swa', 'swa', 'swa'),
    'sv': ('Indo-European', 'Swedish', 'Svenska', 'sv', 'swe', 'swe', 'swe'),
    'ta': ('Dravidian', 'Tamil', 'தமிழ்', 'ta', 'tam', 'tam', 'tam'),
    'te': ('Dravidian', 'Telugu', 'తెలుగు', 'te', 'tel', 'tel', 'tel'),
    'tg': ('Indo-European', 'Tajik', 'тоҷикӣ, toçikī, تاجیکی‎', 'tg', 'tgk', 'tgk', 'tgk'),
    'th': ('Tai–Kadai', 'Thai', 'ไทย', 'th', 'tha', 'tha', 'tha'),
    'bo': ('Sino-Tibetan', 'Tibetan', 'བོད་ཡིག', 'bo', 'bod', 'tib', 'bod'),
    'tk': ('Turkic', 'Turkmen', 'Türkmen, Түркмен', 'tk', 'tuk', 'tuk', 'tuk'),
    'tl': ('Austronesian', 'Tagalog', 'Wikang Tagalog', 'tl', 'tgl', 'tgl', 'tgl'),
    'tr': ('Turkic', 'Turkish', 'Türkçe', 'tr', 'tur', 'tur', 'tur'),
    'tt': ('Turkic', 'Tatar', 'татар теле, tatar tele', 'tt', 'tat', 'tat', 'tat'),
    'ug': ('Turkic', 'Uyghur', 'ئۇيغۇرچە‎, Uyghurche', 'ug', 'uig', 'uig', 'uig'),
    'uk': ('Indo-European', 'Ukrainian', 'Українська', 'uk', 'ukr', 'ukr', 'ukr'),
    'ur': ('Indo-European', 'Urdu', 'اردو', 'ur', 'urd', 'urd', 'urd'),
    'uz': ('Turkic', 'Uzbek', 'Oʻzbek, Ўзбек, أۇزبېك‎', 'uz', 'uzb', 'uzb', 'uzb'),
    'vi': ('Austroasiatic', 'Vietnamese', 'Tiếng Việt', 'vi', 'vie', 'vie', 'vie'),
    'vo': ('Constructed', 'Volapük', 'Volapük', 'vo', 'vol', 'vol', 'vol'),
    'wa': ('Indo-European', 'Walloon', 'Walon', 'wa', 'wln', 'wln', 'wln'),
    'cy': ('Indo-European', 'Welsh', 'Cymraeg', 'cy', 'cym', 'wel', 'cym'),
    'fy': ('Indo-European', 'Western Frisian', 'Frysk', 'fy', 'fry', 'fry', 'fry'),
    'yi': ('Indo-European', 'Yiddish', 'ייִדיש', 'yi', 'yid', 'yid', 'yid'),
    'yo': ('Niger–Congo', 'Yoruba', 'Yorùbá', 'yo', 'yor', 'yor', 'yor'),
    'als': ('Indo-European', 'Tosk Albanian', 'toskë', '', '', '', 'als'),
    'ast': ('Indo-European', 'Asturian', 'Asturianu', '', 'ast', '', 'ast'),
    'bar': ('Indo-European', 'Bavarian', 'Boarisch', '', '', '', 'bar'),
    'bpy': ('Indo-European', 'Bishnupriya Manipuri', 'বিষ্ণুপ্রিয়া মণিপুরী', '', '', '', 'bpy'),
    'bxr': ('Mongolic', 'Buryat', 'буряад хэлэн buryaad xelen', '', 'bua', '', 'bxr'),
    'ceb': ('Austronesian', 'Cebuano', 'Bisayâ', '', 'ceb', '', 'ceb'),
    'bcl': ('Austronesian', 'Central Bicolano', 'Bicolano Central', '', '', '', 'bcl'),
    'arz': ('Afro-Asiatic', 'Egyptian Arabic', 'اللهجة المصرية', '', '', '', 'arz'),
    'eml': ('Indo-European', 'Emilian Romagnol', '', '', '', '', 'eml'),
    'myv': ('Uralic', 'Erzya', 'eŕźań keĺ', '', 'myv', '', 'myv'),
    'hif': ('Indo-European', 'Fiji Hindi', 'फ़िजी बात', '', '', '', 'hif'),
    'gom': ('Indo-European', 'Goan Konkani', 'कोंकणी', '', 'kok', '', 'kok'),
    'mrj': ('Uralic', 'Hill Mari', 'Кырык мары йӹлмӹ', '', '', '', 'mrj'),
    'ilo': ('Austronesian', 'Ilokano', 'Ilokano', '', 'ilo', '', 'ilo'),
    'xal': ('Mongolic', 'Kalmyk', 'Хальмг келн', '', 'xal', '', 'xal'),
    'pam': ('Austronesian', 'Kapampangan', 'Amánung Kapampangan', '', 'pam', '', 'pam'),
    'krc': ('Turkic', 'Karachay Balkar', 'Къарачай-Малкъар тил', '', 'krc', '', 'krc'),
    'ckb': ('Indo-European', 'Kurdish (Sorani)', 'کوردیی ناوەندی', '', '', '', 'ckb'),
    'lez': ('Northeast Caucasian', 'Lezgian', 'lezgi č\'al', '', 'lez', '', 'lez'),
    'jbo': ('Constructed', 'Lojban', 'la .lojban.', '', 'jbo', '', 'jbo'),
    'lmo': ('Indo-European', 'Lombard', 'lumbàart', '', '', '', 'lmo'),
    'nds': ('Indo-European', 'Low Saxon', 'Plattdütsch', '', 'nds', '', 'nds'),
    'dsb': ('Indo-European', 'Lower Sorbian', 'dolnoserbšćina', '', 'dsb', '', 'dsb'),
    'mai': ('Indo-European', 'Maithili', 'मैथिली/মৈথিলী', '', 'mai', '', 'mai'),
    'mzn': ('Indo-European', 'Mazandarani', 'مازندرانی', '', '', '', 'mzn'),
    'mhr': ('Uralic', 'Meadow Mari', 'олыкмарла', '', '', '', 'mhr'),
    'min': ('Austronesian', 'Minangkabau', 'اسو مينڠكاباو‎', '', 'min', '', 'min'),
    'xmf': ('Kartvelian', 'Mingrelian', 'მარგალური ნინა', '', '', '', 'xmf'),
    'mwl': ('Indo-European', 'Mirandese', 'Mirandés', '', 'mwl', '', 'mwl'),
    'nah': ('Uto-Aztecan', 'Nahuatl', 'Nāhuatl', '', 'nah', '', 'nah'),
    'nap': ('Indo-European', 'Neapolitan', 'napulitano', '', 'nap', '', 'nap'),
    'new': ('Sino-Tibetan', 'Newar', 'नेवाः भाय् Nevāh Bhāy', '', 'new', '', 'new'),
    'frr': ('Indo-European', 'North Frisian', 'Frasch', '', 'frr', '', 'frr'),
    'lrc': ('Indo-European', 'Northern Luri', 'لُری', '', '', '', 'lrc'),
    'pfl': ('Indo-European', 'Palatinate German', 'Pälzisch', '', '', '', 'pfl'),
    'pms': ('Indo-European', 'Piedmontese', 'piemontèis', '', '', '', 'pms'),
    'rue': ('Indo-European', 'Rusyn', 'русиньскый язык', '', '', '', 'rue'),
    'sah': ('Turkic', 'Sakha', 'саха тыла', '', 'sah', '', 'sah'),
    'sco': ('Indo-European', 'Scots', 'Lowland Scots', '', 'sco', '', 'sco'),
    'sh': ('Indo-European', 'Serbo Croatian', 'srpskohrvatski / hrvatskosrpski', 'sh', 'scr', '', 'hbs'),
    'scn': ('Indo-European', 'Sicilian', 'sìculu', '', 'scn', '', 'scn'),
    'azb': ('Turkic', 'Southern Azerbaijani', 'آذربایجان دیلی‎', 'az', 'aze', '', 'aze'),
    'tyv': ('Turkic', 'Tuvan', 'тыва дыл', '', 'tyv', '', 'tyv'),
    'hsb': ('Indo-European', 'Upper Sorbian', 'hornjoserbšćina', '', 'hsb', '', 'hsb'),
    'vec': ('Indo-European', 'Venetian', 'łéngoa vèneta', '', '', '', 'vec'),
    'vep': ('Uralic', 'Vepsian', 'vepsän kelʹ', '', '', '', 'vep'),
    'war': ('Austronesian', 'Waray', 'Winaray', '', 'war', '', 'war'),
    'vls': ('Indo-European', 'West Flemish', 'West-Vlaams', '', '', '', 'vls'),
    'pnb': ('Indo-European', 'Western Punjabi', 'ਪੰਜਾਬੀ پن٘جابی', 'pa', 'pan', '', 'pnb'),
    'wuu': ('Sino-Tibetan', 'Wu', '吳語/吴语', '', '', '', 'wuu'),
    'diq': ('Indo-European', 'Zazaki', 'Kirmanjki', '', 'zza', '', 'zza'),
    'cbk': ('Spanish-based creole', 'Zamboanga Chavacano', 'Chabacano', '', '', '', 'cbk'),
    'dty': ('Indo-European', 'Doteli', 'डोटेली', '', '', '', 'dty'),
    'yue': ('Sino-Tibetan', 'Cantonese', '粵語/粤语', '', '', '', 'yue'),
}


# https://github.com/nltk/nltk_data/blob/gh-pages/packages/tokenizers/punkt.xml
# ll ~/nltk_data/tokenizers/punkt
# less ~/nltk_data/tokenizers/punkt/README
PUNKT_LANGUAGES = {
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'et': 'estonian',
    'fi': 'finnish',
    'fr': 'french',
    'de': 'german',
    'el': 'greek',
    'it': 'italian',
    'ml': 'malayalam',
    'no': 'norwegian',
    'pl': 'polish',
    'pt': 'portuguese',
    'ru': 'russian',
    'sl': 'slovene',
    'es': 'spanish',
    'sv': 'swedish',
    'tr': 'turkish',
}


PunktLanguagesEnum = Enum(
    'PunktLanguagesEnum',
    {code: code for code in PUNKT_LANGUAGES.keys()}
)
